In [1]:
pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv

Requirement already satisfied: sqlalchemy in c:\users\marin\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\marin\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: pandas in c:\users\marin\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: matplotlib in c:\users\marin\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\marin\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: python-dotenv in c:\users\marin\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: greenlet>=1 in c:\users\marin\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\marin\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\marin\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\marin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\marin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\marin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\marin\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\marin\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\marin\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\marin\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\marin\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\marin\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\marin\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\marin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [48]:
from datetime import date
import requests 
import json 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import sqlalchemy as sa
from sqlalchemy import create_engine, text, MetaData, Table
from sqlalchemy.orm import sessionmaker

In [49]:
from dotenv import load_dotenv
import os
print(os.getcwd())
load_dotenv("new.env",override=True)
db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")
db_name = os.getenv("DB_NAME")
db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT")

C:\Users\marin\integration python +sql

In [50]:
connection_string = (f"mysql+pymysql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}")

In [51]:
engine = create_engine(connection_string,
                       pool_size=2,
                       max_overflow=20,
                       pool_pre_ping=True,
                       echo=False)

In [52]:
try:
  with engine.connect() as conn :
    result = conn.execute(text("SELECT 1"))
    
  print("✅ Підключення до БД успішне!")

  print(f" {db_user}@{db_host}:{db_port}/{db_name}")
  print(f" Engine: {engine}")
  

except Exception as e:
  print(f"❌ Помилка підключення: {e}")

✅ Підключення до БД успішне!
 root@127.0.0.1:3308/classicmodels
 Engine: Engine(mysql+pymysql://root:***@127.0.0.1:3308/classicmodels)

Завдання 1: Оновлення інформації про клієнта (2 бали)
Створіть функцію для оновлення контактної інформації клієнта за його номером з наступними можливостями:

Оновлення телефону клієнта
Оновлення email (якщо поле існує в таблиці)
Опціонально, якщо вам хочеться більше практики:

Логування змін в окрему таблицю
Використайте підхід з параметризованими запитами через text() та UPDATE оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом

  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [53]:
check = text("""
SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
  """)
df_check = pd.read_sql(check,engine)
df_check

               COLUMN_NAME DATA_TYPE
0             addressLine1   varchar
1             addressLine2   varchar
2                     city   varchar
3         contactFirstName   varchar
4          contactLastName   varchar
5                  country   varchar
6              creditLimit   decimal
7             customerName   varchar
8           customerNumber       int
9                    phone   varchar
10              postalCode   varchar
11  salesRepEmployeeNumber       int
12                   state   varchar

In [54]:
def update_client_information(engine,customerNumber,new_phone):
    check_customer = text("""
    SELECT contactFirstname,contactLastname
    FROM customers
    WHERE customerNumber = :customerNumber
    """)
    with engine.connect() as conn:
        result = conn.execute(check_customer,{'customerNumber': customerNumber})
        customer = result.fetchone()
        if not customer:
            print(f"customer{'customerNumber'} not found")
            return False
        print("Customer exists:", customer)
    with engine.connect() as conn:
        with conn.begin():
            update_phone = text("""
            UPDATE customers
            SET phone = :phone
            WHERE customerNumber = :customerNumber
            """)
            conn.execute(update_phone,{"phone": new_phone,"customerNumber":customerNumber})
    print(f"Phone updated for customer{customerNumber}")

In [55]:
update_client_information(engine,247,'1245656')

Customer exists: ('Renate ', 'Messner')
Phone updated for customer247

In [56]:
check_changes = text("""
    SELECT contactFirstname,contactLastname,phone
    FROM customers
    WHERE customerNumber = '247'
    """)
df_changes = pd.read_sql(check_changes,engine)
df_changes

  contactFirstname contactLastname    phone
0          Renate          Messner  1245656

Завдання 2: Створення нового замовлення з транзакцією (5 балів)
Реалізуйте процес створення нового замовлення з наступними кроками в одній транзакції:

Створення запису в таблиці orders
Додавання товарних позицій в orderdetails
Перевірка наявності товарів на складі
Зменшення кількості товарів на складі
Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [57]:
def new_order (engine,customerNumber,productCode,quantityOrdered):
    with engine.begin() as conn:
        new_order_number = conn.execute(text("""
        SELECT MAX(orderNumber)+1 
        FROM orders
        """)).scalar()
        conn.execute(text("""
        INSERT INTO orders 
        (orderNumber,orderDate,requiredDate,status,customerNumber)
        VALUES (:orderNumber,:orderDate,:requiredDate,:status,:customerNumber)"""),
                     {"orderNumber": new_order_number,
                      "orderDate": date.today(),
                      "requiredDate":date.today(),
                      "status":"In Process",
                      "customerNumber":customerNumber})
        product = conn.execute(text("""
        SELECT buyPrice, quantityInStock
        FROM products
        WHERE productCode = :productCode
        """), {"productCode": productCode}).fetchone()
        if not product:
            print ("product not found")
            return 
        if product.quantityInStock <quantityOrdered:
            print("not enough in stock")
            return
        conn.execute(text("""
        INSERT INTO orderdetails
        (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
        VALUES(:orderNumber, :productCode, :quantityOrdered, :priceEach, :orderLineNumber)"""),
                     {"orderNumber":new_order_number,
                      "productCode":productCode, 
                      "quantityOrdered":quantityOrdered,
                      "priceEach": product.buyPrice,
                      "orderLineNumber": 1})
        conn.execute(text("""
        UPDATE products
        SET quantityInStock = quantityInStock - :quantity
        WHERE productCode = :productCode """),{
        "quantity": quantityOrdered,
        "productCode": productCode})
        print(f"Order {new_order_number} created")

In [58]:
new_order(engine,247,"S10_1678",5)

Order 10426 created

In [64]:
pd.read_sql("""
SELECT orderNumber, orderDate, status, customerNumber
FROM orders
ORDER BY orderNumber DESC
LIMIT 1
""",engine)

   orderNumber   orderDate      status  customerNumber
0        10426  2026-03-09  In Process             247

In [63]:
pd.read_sql("""
SELECT *
FROM orderdetails
ORDER BY orderNumber DESC
LIMIT 1
""",engine)

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        10426    S10_1678                5      48.81                1

In [62]:
pd.read_sql("""
SELECT productCode, quantityInStock
FROM products 
WHERE productCode = 'S10_1678'""",engine)

  productCode  quantityInStock
0    S10_1678             7928