<a href="https://colab.research.google.com/github/marinamaer123/new_test/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22HW_16_1_%D0%9F%D1%80%D0%BE%D0%B3%D0%BD%D0%BE%D0%B7%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%BE%D1%80%D0%B5%D0%BD%D0%B4%D0%BD%D0%BE%D1%97_%D0%BF%D0%BB%D0%B0%D1%82%D0%B8_%D0%B7%D0%B0_%D0%B6%D0%B8%D1%82%D0%BB%D0%BE_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнє завдання: Прогнозування орендної плати за житло

## Мета завдання
Застосувати знання з лекції для побудови моделі лінійної регресії, що прогнозує орендну плату за житло в Індії. Ви пройдете весь цикл вирішення задачі машинного навчання: від дослідницького аналізу до оцінки якості моделі.

## Опис датасету
**House Rent Prediction Dataset** містить інформацію про 4700+ оголошень про оренду житла в Індії з такими параметрами:
- **BHK**: Кількість спалень, залів, кухонь
- **Rent**: Орендна плата (цільова змінна)
- **Size**: Площа в квадратних футах
- **Floor**: Поверх та загальна кількість поверхів
- **Area Type**: Тип розрахунку площі
- **Area Locality**: Район
- **City**: Місто
- **Furnishing Status**: Стан меблювання
- **Tenant Preferred**: Тип орендаря
- **Bathroom**: Кількість ванних кімнат
- **Point of Contact**: Контактна особа

---

## Завдання 1: Завантаження та перший огляд даних (1 бал)

**Що потрібно зробити:**
1. Завантажте дані з файлу `House_Rent_Dataset.csv`
2. Виведіть розмір датасету
3. Покажіть перші 5 рядків
4. Виведіть загальну інформацію про дані (включно з типами даних та кількістю значень)

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [34]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
df = pd.read_csv('/content/drive/MyDrive/House_Rent_Dataset.csv')

In [35]:
df.shape

(4746, 12)

In [36]:
df.head(5)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   object
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
dtypes: int64(4), object(8)
memory usage: 445.1+ KB

## Завдання 2: Дослідницький аналіз даних (EDA) (5 балів)

**Що потрібно зробити:**
1. **Аналіз пропущених значень.** Перевірте наявність і відсоток пропущених значень у кожній колонці
2. **Базова статистика.** Обчисліть базову статистику (середнє, квартилі, стандартне відхилення) для числових змінних.
3. **Аналіз цільової змінної.** Побудуйте гістограму розподілу цільової змінної (Rent)
4. **Робота з викидами.** Знайдіть та видаліть викиди в цільовій змінній (якщо є). Визначити викиди можна будь-яким зрозумілим для вас способом, як варіант - таким, що використовується в побудові box-plot (https://en.wikipedia.org/wiki/Box_plot#Example_with_outliers).
5. **Аналіз категоріальних змінних.** Виведіть кількість унікальних значень для кожної з категоріальних колонок.

In [38]:
missing_data = df.isnull().sum()

In [39]:
missing_percent = (missing_data/len(df)) * 100
missing_percent

Posted On            0.0
BHK                  0.0
Rent                 0.0
Size                 0.0
Floor                0.0
Area Type            0.0
Area Locality        0.0
City                 0.0
Furnishing Status    0.0
Tenant Preferred     0.0
Bathroom             0.0
Point of Contact     0.0
dtype: float64

In [40]:
stats = df.describe()
stats.round(2)

           BHK        Rent     Size  Bathroom
count  4746.00     4746.00  4746.00   4746.00
mean      2.08    34993.45   967.49      1.97
std       0.83    78106.41   634.20      0.88
min       1.00     1200.00    10.00      1.00
25%       2.00    10000.00   550.00      1.00
50%       2.00    16000.00   850.00      2.00
75%       3.00    33000.00  1200.00      2.00
max       6.00  3500000.00  8000.00     10.00

In [41]:
fig = px.histogram(
    df.Rent,
    x='Rent',
    nbins=100,
    title='Розподіл цільової змінної',
    labels={'rent_count': 'Ціна оренди', 'count': 'Кількість варіантів'}
)
fig.update_layout(
    showlegend=False,
    height=400
)
fig.show()

In [42]:
numeric_cols = df.select_dtypes(include = 'number').columns
clean_df = df.copy()
for col in numeric_cols:
  Q1 = clean_df[col].quantile(0.25)
  Q3 = clean_df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  clean_df = clean_df[(clean_df[col] >= lower) & (clean_df[col] <= upper)]

In [43]:
categorical_cols = clean_df.select_dtypes(include = 'object').columns
clean_df[categorical_cols].nunique()

Posted On              80
Floor                 330
Area Type               3
Area Locality        1955
City                    6
Furnishing Status       3
Tenant Preferred        3
Point of Contact        3
dtype: int64


## Завдання 3: Аналіз кореляцій та взаємозв'язків (3 бали)

**Що потрібно зробити:**
1. Обчисліть матрицю кореляцій для числових змінних
2. Візуалізуйте кореляційну матрицю за допомогою heatmap
3. Побудуйте scatter plot між Size та Rent
4. Проаналізуйте взаємозв'язок між BHK та Rent за допомогою boxplot (який розподіл плати для різних значень BHK)

In [44]:
metrics_df = clean_df[['BHK','Rent','Size','Bathroom']]
correlation_matrix = metrics_df.corr()
correlation_matrix

               BHK      Rent      Size  Bathroom
BHK       1.000000  0.354752  0.677057  0.723999
Rent      0.354752  1.000000  0.320104  0.471460
Size      0.677057  0.320104  1.000000  0.651065
Bathroom  0.723999  0.471460  0.651065  1.000000

In [45]:
fig = px.imshow(
    correlation_matrix,
    text_auto='.2f',
    color_continuous_scale='RdBu_r',
    title='Кореляція між метриками взаємодії',
    labels=dict(color="Кореляція")
)
fig.update_layout(height=500)
fig.show()

In [46]:
fig = px.scatter(clean_df, x = 'Size',y = 'Rent',title = 'BHK vs Rent')
fig.show()

In [47]:
fig = px.box(clean_df,x = 'BHK',y = 'Rent',title = 'взаємозвязок між BHK та Rent' )
fig.show()

## Завдання 4: Feature Engineering та підготовка даних (4 бали)

**Що потрібно зробити:**
1. Закодуйте категоріальні змінні за допомогою One-Hot Encoding. Пригадайте, що в лекції ми говорили щодо кодування кат. змінних з великої кількістю різних значень і як працювати з такими випадками. Ви можете закодувати не всі кат. змінні, а лише ті, що вважаєте за потрібні (скажімо ті, що мають відносно небагато різних значень).
2. **Опціонально (по 0.5 бала за кожну доцільну ознаку):** Додайте нові ознаки, обчислені на основі наявних даних, які б на ваш погляд були корисними для моделі
3. Виберіть ознаки для побудови моделі (виключіть непотрібні колонки). Виключити можна, наприклад, ті колонки, які мають категоріальний тип і забагато (більше 20) різних значень. Треба виключити хоча б 1 колонку.
4. Розділіть дані на ознаки (X) та цільову змінну (y)
5. Застосуйте стандартизацію до числових ознак

In [48]:
Area_dummies = pd.get_dummies(clean_df['Area Type'], prefix='')
Area_dummies.head().astype(int)

   _Built Area  _Carpet Area  _Super Area
0            0             0            1
1            0             0            1
2            0             0            1
3            0             0            1
4            0             1            0

In [49]:
City_dummies = pd.get_dummies(clean_df['City'], prefix='City')
City_dummies.head().astype(int)

,City_Bangalore,City_Chennai,City_Delhi,City_Hyderabad,City_Kolkata,City_Mumbai
0,0,0,0,0,1,0
1,0,0,0,0,1,0
2,0,0,0,0,1,0
3,0,0,0,0,1,0
4,0,0,0,0,1,0

In [50]:
Furnishing_dummies = pd.get_dummies(clean_df['Furnishing Status'], prefix='')
Furnishing_dummies.head().astype(int)

   _Furnished  _Semi-Furnished  _Unfurnished
0           0                0             1
1           0                1             0
2           0                1             0
3           0                0             1
4           0                0             1

In [51]:
Tenant_dummies = pd.get_dummies(clean_df['Tenant Preferred'], prefix='Tenant')
Tenant_dummies.head().astype(int)

   Tenant_Bachelors  Tenant_Bachelors/Family  Tenant_Family
0                 0                        1              0
1                 0                        1              0
2                 0                        1              0
3                 0                        1              0
4                 1                        0              0

In [52]:
Contact_dummies = pd.get_dummies(clean_df['Point of Contact'], prefix='')
Contact_dummies.head().astype(int)

   _Contact Agent  _Contact Builder  _Contact Owner
0               0                 0               1
1               0                 0               1
2               0                 0               1
3               0                 0               1
4               0                 0               1

In [53]:
clean_df['floor_clean'] = clean_df['Floor'].str.replace('Ground','0').str.extract(r'(\d+)').astype(int)

In [54]:
df_clean_enr = pd.concat([clean_df, Area_dummies,City_dummies,Furnishing_dummies,Tenant_dummies,Contact_dummies], axis=1)

In [55]:
df_clean_enr.head(3)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,...,City_Mumbai,_Furnished,_Semi-Furnished,_Unfurnished,Tenant_Bachelors,Tenant_Bachelors/Family,Tenant_Family,_Contact Agent,_Contact Builder,_Contact Owner
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,...,False,False,False,True,False,True,False,False,False,True
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,...,False,False,True,False,False,True,False,False,False,True
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,...,False,False,True,False,False,True,False,False,False,True

In [56]:
df_clean_enr2 = df_clean_enr[['BHK', 'Rent', 'Size',
       'Bathroom',  'floor_clean', '_Built Area',
       '_Carpet Area', '_Super Area', 'City_Bangalore', 'City_Chennai',
       'City_Delhi', 'City_Hyderabad', 'City_Kolkata', 'City_Mumbai',
       '_Furnished', '_Semi-Furnished', '_Unfurnished', 'Tenant_Bachelors',
       'Tenant_Bachelors/Family', 'Tenant_Family', '_Contact Agent',
       '_Contact Builder', '_Contact Owner']]

In [57]:
features = df_clean_enr2[['BHK', 'Size',
       'Bathroom',  'floor_clean', '_Built Area',
       '_Carpet Area', '_Super Area', 'City_Bangalore', 'City_Chennai',
       'City_Delhi', 'City_Hyderabad', 'City_Kolkata', 'City_Mumbai',
       '_Furnished', '_Semi-Furnished', '_Unfurnished', 'Tenant_Bachelors',
       'Tenant_Bachelors/Family', 'Tenant_Family', '_Contact Agent',
       '_Contact Builder', '_Contact Owner']]
features[['_Built Area','_Carpet Area','_Super Area',	'City_Bangalore',	'City_Chennai','City_Delhi', 'City_Hyderabad', 'City_Kolkata', 'City_Mumbai',
       '_Furnished', '_Semi-Furnished', '_Unfurnished', 'Tenant_Bachelors',
       'Tenant_Bachelors/Family', 'Tenant_Family', '_Contact Agent',
       '_Contact Builder', '_Contact Owner']].astype(int)

,_Built Area,_Carpet Area,_Super Area,City_Bangalore,City_Chennai,City_Delhi,City_Hyderabad,City_Kolkata,City_Mumbai,_Furnished,_Semi-Furnished,_Unfurnished,Tenant_Bachelors,Tenant_Bachelors/Family,Tenant_Family,_Contact Agent,_Contact Builder,_Contact Owner
0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1
1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1
2,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1
3,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1
4,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4740,0,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1
4741,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1
4743,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0
4744,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0
4745,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1

In [58]:
target = df_clean_enr2['Rent']

In [59]:
X = features
Y = target
print(f"\nРозмір X (ознак): {X.shape}")
print(f"Розмір y (цілі): {Y.shape}")

Розмір X (ознак): (4078, 22)
Розмір y (цілі): (4078,)

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns, index=X.index)

## Завдання 5: Розділення даних та навчання моделі (3 бали)

**Що потрібно зробити:**
1. Розділіть дані на навчальну (80%) та тестову (20%) вибірки.
2. Створіть модель лінійної регресії.
3. Навчіть модель на навчальних даних.
4. Виведіть усі коефіцієнти моделі (ваги) та напишіть, які 2 ознаки найбільше впливають на прогноз.
5. Зробіть прогнози на тренувальній та тестовій вибірках.

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled_df, Y,
    test_size=0.2,
    random_state=42)

In [63]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [64]:
for feature, weight in zip(model.feature_names_in_, model.coef_):
    print(f"{feature}: {weight:.2f}")

print(f"\nЗміщення (intercept): {model.intercept_:.2f}")

BHK: 2453.72
Size: 2855.32
Bathroom: 1827.34
floor_clean: 1289.90
_Built Area: -32.38
_Carpet Area: 20.51
_Super Area: -19.06
City_Bangalore: -840.41
City_Chennai: -1078.05
City_Delhi: 275.29
City_Hyderabad: -1659.41
City_Kolkata: -1614.53
City_Mumbai: 5276.01
_Furnished: 1088.18
_Semi-Furnished: -25.83
_Unfurnished: -693.92
Tenant_Bachelors: 332.49
Tenant_Bachelors/Family: 75.98
Tenant_Family: -558.45
_Contact Agent: 1759.94
_Contact Builder: -16.26
_Contact Owner: -1758.75

Зміщення (intercept): 18631.89

Найбільше впливають City_Mumbai та Size.

---

In [65]:
y_train_pred = model.predict(X_train)


y_test_pred = model.predict(X_test)


comparison = pd.DataFrame({
    'Реальні Ціни': y_test.values[:10],
    'Прогнозовані Ціни': y_test_pred[:10].round(0),
    'Помилка': (y_test.values[:10] - y_test_pred[:10]).round(0)
})
print("Приклади прогнозів на тестовій вибірці:")
print(comparison)

Приклади прогнозів на тестовій вибірці:
   Реальні Ціни  Прогнозовані Ціни  Помилка
0         22000            14173.0   7827.0
1         10000            10954.0   -954.0
2         30000            23520.0   6480.0
3         13000            18123.0  -5123.0
4          6500            11045.0  -4545.0
5          3000             1213.0   1787.0
6         54500            34531.0  19969.0
7         26000            31093.0  -5093.0
8         50000            35238.0  14762.0
9         51500            49685.0   1815.0

## Завдання 6: Оцінка якості моделі (2 бали)

**Що потрібно зробити:**
1. Обчисліть MAE, RMSE та R² для навчальної та тестової вибірок
2. Порівняйте метрики та зробіть висновок про якість моделі
3. Проаналізуйте і дайте висновок, чи є ознаки перенавчання або недонавчання (**Нагадування**: перенавчання - коли модель дуже добре працює на тренувальних даних, але погано на тестових; недонавчання - коли модель погано працює навіть на тренувальних даних)
4. Побудуйте графік розсіювання "реальні vs прогнозовані значення" та зробіть висновок про якість моделі

In [66]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test,y_test_pred)
mse = mean_squared_error(y_test,y_test_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_test_pred)
print("="*50)
print("МЕТРИКИ ЯКОСТІ МОДЕЛІ (на тестовій вибірці):")
print("="*50)
print(f"\nMAE: {mae:.2f} ")
print(f"RMSE: {rmse:.2f} ")
print(f"R²: {r2:.3f}")

==================================================
МЕТРИКИ ЯКОСТІ МОДЕЛІ (на тестовій вибірці):
==================================================

MAE: 5436.97
RMSE: 7396.45
R²: 0.662

In [67]:
mae2 = mean_absolute_error(y_train,y_train_pred)
mse2 = mean_squared_error(y_train,y_train_pred)
rmse2 = np.sqrt(mse)
r22 = r2_score(y_train,y_train_pred)
print("="*50)
print("МЕТРИКИ ЯКОСТІ МОДЕЛІ (на тестовій вибірці):")
print("="*50)
print(f"\nMAE: {mae2:.2f} ")
print(f"RMSE: {rmse2:.2f} ")
print(f"R²: {r22:.3f}")

==================================================
МЕТРИКИ ЯКОСТІ МОДЕЛІ (на тестовій вибірці):
==================================================

MAE: 5252.88
RMSE: 7396.45
R²: 0.698

При порівнянні R² ми бічимо що модель працює доволі добре,попри те різниця RMSE з MAE  вказує на те що модель в деяких випадках помиляється доволі сильно.Можливо на дуже дешевих та дуже дорогих приміщеннях. Ознак перенавчання або недонвчання не виявлено.

In [68]:
fig = px.scatter(
    x=y_test,
    y=y_test_pred,
    title='Реальні vs Прогнозовані ціни (тестова вибірка)',
    labels={'x': 'Реальні ціни', 'y': 'Прогнозовані ціни'},
    opacity=0.6
)

# Додаємо ідеальну лінію (де прогноз = реальність)
max_val = max(y_test.max(), y_test_pred.max())
fig.add_trace(
    go.Scatter(
        x=[0, max_val],
        y=[0, max_val],
        mode='lines',
        name='Ідеальний прогноз',
        line=dict(color='red', dash='dash')
    )
)

fig.update_layout(height=500)
fig.show()

Деякі прогнози є доволі точними ,попри те є викиди де помилка більше ніж на 100% вартості.Це свідчить про переоцінку та недооцінку в деяких випадках.

## Завдання 7: Аналіз помилок (4 бали)

**Що потрібно зробити:**
1. Обчисліть помилки (residuals = реальні - прогнозовані значення)
2. Побудуйте гістограму розподілу помилок
3. Створіть scatter plot помилок відносно величини прогнозованих значень. Чи росте помилка з ростом прогнозованого значення?
4. Знайдіть 5 прогнозів з найбільшими помилками
5. Проаналізуйте, на яких типах житла модель помиляється найбільше. Типи можна розрізняти за кількістю кімнат чи містом, наприклад.
6. Подумайте і напишіть, які наступні кроки ви б зробили, аби поліпшити якість моделі. Опціонально можна їх зробити і ми перевіримо :)

In [69]:
residuals = y_test - y_test_pred

In [70]:
fig = px.histogram(
    x=residuals,
    nbins=50,
    title='Розподіл помилок прогнозування',
    labels={'x': 'Помилка (реальні - прогнозовані)', 'count': 'Кількість'},
    color_discrete_sequence=['#e74c3c']
)
fig.add_vline(x=0, line_dash="dash", line_color="black", annotation_text="Ідеальний прогноз")
fig.update_layout(height=400)
fig.show()

In [73]:
fig = px.scatter(
    x=y_test_pred,
    y=residuals,
    title='Залежність помилок від прогнозованих значень',
    labels={'x': 'Прогнозовані ціни', 'y': 'Помилка'},
    opacity=0.5)
fig.add_hline(y=0, line_dash="dash", line_color="red", annotation_text="Без помилки")

fig.update_layout(height=400)
fig.show()

Так,помилка росте з ростом прогназованого значення.

In [76]:
errors_df = pd.DataFrame({
    'real': y_test.values,
    'predicted': y_test_pred,
    'error': np.abs(residuals)
})
top_errors = errors_df.nlargest(5,'error')

In [77]:
top_errors

       real     predicted         error
549    8000  40007.444873  32007.444873
1090  65000  33386.169214  31613.830786
1908  65000  35027.555718  29972.444282
2826  60000  30683.122216  29316.877784
1411   6500  34879.777880  28379.777880

In [82]:
df_clean_enr2.loc[[549,1090,1908,2826,1411]]

,BHK,Rent,Size,Bathroom,floor_clean,_Built Area,_Carpet Area,_Super Area,City_Bangalore,City_Chennai,...,City_Mumbai,_Furnished,_Semi-Furnished,_Unfurnished,Tenant_Bachelors,Tenant_Bachelors/Family,Tenant_Family,_Contact Agent,_Contact Builder,_Contact Owner
549,2,8000,650,2,9,False,True,False,False,False,...,True,False,True,False,False,False,True,True,False,False
1090,2,65000,935,2,2,False,False,True,False,False,...,True,False,True,False,False,True,False,False,False,True
1908,3,65000,1480,2,7,False,True,False,True,False,...,False,True,False,False,False,False,True,True,False,False
2826,3,60000,1600,3,3,False,False,True,False,False,...,False,False,True,False,False,True,False,False,False,True
1411,1,6500,422,2,9,False,True,False,False,False,...,True,False,True,False,False,False,True,True,False,False

Я би спробувала розділити усі дані на 3 сегменти ,де житло до 20000 у першій групі,від 20к до 60к у другій та окремо найдорожчі та побудувала би модель для кожного сегменту,тому що помилка зростає зі зростанням реальноІ ціни на житло.